version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/
hooks:
  ApplicationStart:
    - location: ./codedeploy/start_server.sh
      timeout: 300
      runas: ubuntu
  AfterInstall:
     - location: ./codedeploy/stop_server.sh
       timeout: 300  
       runas: ubuntu  
  