version: 2.1
jobs:
  build:
     docker:
       - image: circleci/openjdk:8-jdk
       - image: circleci/mysql:5.7.30
         environment:
         - MYSQL_ROOT_PASSWORD: sapnaneu
         - MYSQL_DATABASE: Assignment
     steps:
       - checkout
       - run:
           name: Build WAR file
           command:  |
             echo 'test'
             pwd
             ls -al
             cd assignment
             mvn clean install
       - aws-s3/copy:
          from: assignment/pom.xml
          to: 's3://codedeploy.sapnapatel.me'
orbs:
  aws-s3: circleci/aws-s3@1.0.15  