version: 2.1
jobs:
  build:
     docker:
       - image: circleci/openjdk:8-jdk
       - image: circleci/mysql:5.7.30
         environment:
         - MYSQL_ROOT_PASSWORD: sapnaneu
         - MYSQL_DATABASE: Assignment
     steps:
       - checkout
       - run:
           name: Build WAR file
           command:  |
             echo 'test'
             pwd
             ls -al
             cd assignment
             mvn clean install
       - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-access-key-id: AKIAQJCEOWHYPKWK3XPJ
          aws-region: us-east-1
          aws-secret-access-key: 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
          from: assignment
          overwrite: true
          to: 's3://codedeploy.sapnapatel.me/prefix'
      - aws-s3/copy:
          arguments: '--dry-run'
          from: assignment/pom.xml
          to: 's3://codedeploye.sapnapatel.me'
orbs:
  aws-s3: circleci/aws-s3@x.y
version: 2.1      