version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
  aws-code-deploy: circleci/aws-code-deploy@1.0.1  
jobs:
  build:
     docker:
       - image: circleci/openjdk:8-jdk
       - image: circleci/mysql:5.7.30
         environment:
         - MYSQL_ROOT_PASSWORD: sapnaneu
         - MYSQL_DATABASE: Assignment
     steps:
       - checkout
       - run:
           name: Build WAR file
           command:  |
             echo 'test'
             pwd
             ls -al
             cd assignment
             mvn package
             echo 'build successful'
             ls -al
             cd target
             cp assignment-0.0.1-SNAPSHOT.war assignment
             ls -al
             cd
             cd project
             ls -al
             pwd
             zip webapp.zip appspec.yml assignment/assignment-0.0.1-SNAPSHOT.war codedeploy/*.sh
             sudo chmod 775 webapp.zip
             mkdir abc
             cp webapp.zip abc
             cd abc
             unzip webapp.zip
             pwd
             ls -al
       - aws-s3/copy:
          from: webapp.zip
          to: s3://codedeploy.sapnapatel1.me
workflows:
  deploy_application:
    jobs:
      - build
      - aws-code-deploy/deploy:
          application-name: csye6225_webapp
          bundle-bucket: codedeploy.sapnapatel1.me
          bundle-key: webapp
          deployment-group: csye6225-webapp-deployment
          service-role-arn: arn:aws:iam::478806934556:role/CodeDeployServiceRole
