version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15
orbs:
  aws-code-deploy: circleci/aws-code-deploy@1.0.1
jobs:
  build:
     docker:
       - image: circleci/openjdk:8-jdk
       - image: circleci/mysql:5.7.30
         environment:
         - MYSQL_ROOT_PASSWORD: sapnaneu
         - MYSQL_DATABASE: Assignment
     steps:
       - checkout
       - run:
           name: Build WAR file
           command:  |
             echo 'test'
             pwd
             ls -al
             cd assignment
             mvn clean install
             zip -r webapp.zip webapp/
             sudo chmod 775 webapp.zip
             ls
       - aws-s3/copy:
          from: webapp.zip
          to: 's3://codedeploy.sapnapatel1.me'
workflows:
  deploy_application:
    jobs:
      - build
      - aws-code-deploy/deploy:
          application-name: csye6225_webapp
          bundle-bucket: codedeploy.sapnapatel1.me
          bundle-key: webapp.zip
          deployment-group: csye6225-webapp-deployment
