version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:5.7.30
        environment:
        - MYSQL_ROOT_PASSWORD: sapnaneu
        - MYSQL_DATABASE: Assignment
    steps:
      - checkout
      - run:
          name: Build War file
          command:  |
            echo 'testHelloWorld'
            pwd
            ls -al
            cd assignment
            mvn clean install
            mvn clean build


<<<<<<< HEAD
=======
    test:
      working_directory: ~/webapp
        docker:
          - image: circleci/openjdk:8-jdk
          - image: circleci/mysql:5.7.30
          environment:
            - MYSQL_ROOT_PASSWORD: sapnaneu
            - MYSQL_DATABASE: Assignment

        steps:
          - checkout
          - run:
              name: Build WAR
              command:
                echo 'delivery pipeline'
                pwd
                ls -al
                ./mvnw clean install
                ./mvnw spring-boot:run

  workflows:
    version: 2
    build_and_test:
      jobs:
        - build
        - test
>>>>>>> 82825a67a49824bae0722b48b20c908d7d9ebbb2
