version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
      - image: circleci/mysql:5.7.30
        environment:
        - MYSQL_ROOT_PASSWORD: sapnaneu
        - MYSQL_DATABASE: Assignment
    steps:
      - checkout
      - run:
          name: Build War file
          command:  |
            echo 'testHelloWorld'
            pwd
            ls -al
            cd assignment
            mvn clean install
            mvn clean build

