version: 2.1
jobs:
  build:
     docker:
       - image: circleci/openjdk:8-jdk
     steps:
       - checkout
       - run:
           name: Build WAR file
           command:  |
             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
             unzip awscliv2.zip
             sudo ./aws/install
             sudo apt-get update -y
             sudo apt-get install -y less
             echo 'test'
             pwd
             ls -al
             cd assignment
             mvn package
             echo 'successful'
             ls -al
             cd ..
             ls -al
             pwd
             zip -r webapp${CIRCLE_BUILD_NUM}.zip appspec.yml assignment/target/assignment-0.0.1-SNAPSHOT.war codedeploy/start_server.sh
             sudo chmod 775 webapp${CIRCLE_BUILD_NUM}.zip
             ls -al
             aws s3 cp webapp${CIRCLE_BUILD_NUM}.zip s3://codedeploy.sapnapatel1.me             
workflow:
  jobs:
    - build