version: 2.1
jobs:
  build:
     docker:
       - image: circleci/openjdk:8-jdk
       - image: circleci/mysql:5.7.30
         environment:
         - MYSQL_ROOT_PASSWORD: sapnaneu
         - MYSQL_DATABASE: Assignment
     steps:
       - checkout
       - run:
           name: Build WAR file
           command:  |
             echo 'test'
             pwd
             ls -al
             cd assignment
             mvn clean install